spring.application.name=auth-service

server.port=8080

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/deliverx
spring.datasource.username=deliverx_user
spring.datasource.password=deliverx_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Использовать 'validate' в проде
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- JWT ---
# Secret обязательно >= 32 знаков в длину (256 бит) для HS256
# Заменить на рандомную строку: openssl rand -base64 48
app.jwt.secret=deliverx-super-secret-jwt-key-change-in-prod-000
app.jwt.expiration=86400000
