spring.application.name=rates-service
server.port=8080

# Деловые Линии
dellin.appkey=16517875-370E-4C63-9F66-8778E66EF9F9

# Логирование
logging.level.com.deliverx=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
