spring.application.name=user-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=user_user
spring.datasource.password=user_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MUST match auth-service secret for token validation
app.jwt.secret=deliverx-super-secret-jwt-key-change-in-prod-000
